name: Build CLI Executable

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile cli.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cli-${{ matrix.os }}
          path: dist/*
